spring:
  profiles: 
    active: default
#jersey properties
  application:  
    name: core
#redis properties  
  session:  
    store-type: redis
  redis:
    host: localhost
    port: 6379
    timeout: 0
#tomcat details          
server:
  use-forward-headers: true
  port: 8081

security:
  oauth2:
    client:
      clientId: 309209601751-vhdqsq5v2jf16uro88jd6v83ld9i5ui7.apps.googleusercontent.com
      clientSecret: l9VLA12m6___HDxgmw3M6Zl-
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope:
        - openid
        - email
        - profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true